# config/services/credit.yml
service:
  name: "credit-service"

# Credit business logic
credit:
  trial_credits: 100
  low_balance_threshold_percent: 20

# Plugin management
plugin:
  status_cache_ttl: 15
  rate_limit_per_merchant: 100

# Service-specific cache settings
cache:
  ttl_seconds: 60
  
api:
  port: 8000
  external_port: 8000
  
database:
  enabled: true
  
monitoring:
  metrics_enabled: true
  tracing_enabled: true