service: 
  name: notification-service

api:
  port: 8007

email: 
  primary_provider: "sendgrid"
  fallback_provider: "smtp"

rate_limiting:
  enabled: true
  per_hour: 100
  per_day: 1000

template:
  max_size: 1048576      # 1 MB
  render_timeout: 30     # seconds

retry:
  max_attempts: 3
  initial_delay_ms: 1000
  max_delay_ms: 60000

bulk_email:
  default_batch_size: 100
  max_batch_size: 1000
  min_batch_size: 1
  batch_delay_seconds: 1.0
  max_delay_seconds: 60.0
  concurrent_batches: 10