# config/services/webhook-service.yml
service:
  name: "webhook-service"
  version: "1.0.0"
  description: "Receives and processes webhooks from external platforms"
  debug: True
  
api:
  host: "0.0.0.0"
  cors_origins:
    - "http://localhost:3000"

database:
  pool_size: 20           # Higher for webhook volume
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: False

rate_limiting:
  enabled: False          # Webhooks need high throughput
  window_seconds: 60

webhook:
  body_limit_bytes: 2097152      # 2MB
  idempotency_ttl_seconds: 259200  # 72 hours
  max_retries: 10
  ip_allowlist_mode: "disabled"  # disabled/soft/hard
  shopify_ips: []               # Populate with actual Shopify IPs in production
  retry_delay_seconds: 60

logging:
  level: INFO
  format: json
  file_path: "/var/log/webhook-service.log"

cache:
  enabled: True
  ttl_seconds: 259200    # 72 hours for idempotency
  max_connections: 100   # High for concurrent webhooks

monitoring:
  metrics_enabled: True
  tracing_enabled: False
