version: '3.8'

services:
  # ----------------- Single PostgreSQL Instance (like prod) -----------------
  postgres-local:
    image: postgres:15-alpine
    container_name: glam-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-glamlocal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-localpass}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Exposed for local development
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
      - ./infrastructure/scripts/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - glam-local-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-glamlocal}"]
      interval: 10s
      retries: 5
      start_period: 10s

  # ----------------- Message Broker -----------------
  nats-local:
    image: nats:2.10.7-alpine
    container_name: glam-nats-local
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # Monitoring
    command: ["nats-server", "-js", "--store_dir", "/data"]
    volumes:
      - nats-local-data:/data
    networks:
      - glam-local-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      retries: 5
      start_period: 10s

  # ----------------- Email Testing -----------------
  mailhog:
    image: mailhog/mailhog:latest
    container_name: glam-mailhog-local
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI at http://localhost:8025
    networks:
      - glam-local-net
    logging:
      driver: 'none'  # Disable excessive logging

networks:
  glam-local-net:
    driver: bridge

volumes:
  postgres-local-data:
  nats-local-data:
