version: '3.8'

services:
  merchant-service:
    build: .
    ports:
      - "8113:8000"
      - "9090:9090"  # Metrics
    environment:
      - DATABASE_URL=postgresql://merchant:password@postgres:5432/merchant_db
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - BACKEND_API_KEY=test-api-key
      - LOG_LEVEL=INFO
      - DEBUG=false
      - DOCKER_CONTAINER=1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./src:/app/src  # Hot reload
      - ./config:/app/config  # Mount config
    networks:
      - merchant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: merchant_db
      POSTGRES_USER: merchant
      POSTGRES_PASSWORD: password
    ports:
      - "5413:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - merchant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merchant -d merchant_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6313:6379"
    volumes:
      - redis_data:/data
    networks:
      - merchant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10-alpine
    ports:
      - "4213:4222"
      - "8213:8222"  # HTTP monitoring
    command: [
      "nats-server",
      "--jetstream",
      "--store_dir=/data",
      "--http_port=8222"
    ]
    volumes:
      - nats_data:/data
    networks:
      - merchant-network

volumes:
  postgres_data:
  redis_data:
  nats_data:

networks:
  merchant-network:
    driver: bridge

