version: '3.8'

services:
  catalog-service:
    build:
      context: ../..
      dockerfile: services/catalog-service/Dockerfile
    ports:
      - "8118:8000"      # External port mapping
      - "9090:9090"      # Metrics
    environment:
      - DATABASE_URL=postgresql://catalog:password@postgres:5432/catalog_db
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - LOG_LEVEL=INFO
      - DEBUG=false
      - DOCKER_CONTAINER=1
      - APP_API_KEY=${APP_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    networks:
      - catalog-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: password
    ports:
      - "5418:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog -d catalog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6318:6379"
    volumes:
      - redis_data:/data
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10-alpine
    ports:
      - "4218:4222"
      - "8218:8222"  # HTTP monitoring
    command: [
      "nats-server",
      "--jetstream",
      "--store_dir=/data",
      "--http_port=8222"
    ]
    volumes:
      - nats_data:/data
    networks:
      - catalog-network

volumes:
  postgres_data:
  redis_data:
  nats_data:

networks:
  catalog-network:
    driver: bridge

# ================================================================
