global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # NATS Server metrics
  - job_name: 'nats'
    static_configs:
      - targets: ['nats-exporter:7777']
        labels:
          service: 'nats'
          environment: 'local'
