infrastructure:
  nats_url: nats://localhost:4222
  redis_url: redis://localhost:6379

environment: development
debug: true

logging:
  level: INFO
  format: json

api:
  host: 0.0.0.0
  cors_origins: ["*"]
  
monitoring:
  metrics_enabled: true
  tracing_enabled: false
  
service:
  version: "1.0.0"
  
aws:
  region: "us-east-1"
  
email:
  from_domain: "glamyouup.com"
  smtp_port: 587
  
rate_limiting:
  enabled: true
  window_seconds: 60
