# config/shared.yml
environment: local

logging:
  level: DEBUG
  format: json
  file_path: "/var/log/service.log"

monitoring:
  metrics_enabled: true
  tracing_enabled: false

rate_limiting:
  enabled: true
  window_seconds: 60

