# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ab171053318ab7feabfaf0e810fbd76"
name = "Staging-GYU-App"
handle = "StagingGYUApp"
application_url = "https://7e18abe4c748.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bb-staging-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  uri = "https://413e2ec4b6f2.ngrok-free.app/webhooks/relay"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,read_orders,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = ["https://7e18abe4c748.ngrok-free.app/auth/callback", "https://7e18abe4c748.ngrok-free.app/auth/shopify/callback", "https://7e18abe4c748.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
