#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create all databases
    CREATE DATABASE analytics_db;
    CREATE DATABASE billing_db;
    CREATE DATABASE catalog_db;
    CREATE DATABASE credit_db;
    CREATE DATABASE merchant_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE recommendation_db;
    CREATE DATABASE season_compatibility_db;
    CREATE DATABASE selfie_db;
    CREATE DATABASE token_db;
    CREATE DATABASE webhook_db;

    -- Grant all privileges to main user
    GRANT ALL PRIVILEGES ON DATABASE analytics_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE billing_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE catalog_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE credit_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE merchant_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE recommendation_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE season_compatibility_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE selfie_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE token_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE webhook_db TO $POSTGRES_USER;
EOSQL
